{% set version = "0.4-6" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-grplasso
  version: {{ version|replace("-", "_") }}

source:
  fn: grplasso_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/grplasso_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/grplasso/grplasso_{{ version }}.tar.gz
  sha256: 7aded3902f8d4b3303810e992534a26fa21e256e644ad2f248970e661fbd2677

build:
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('grplasso')"  # [not win]
    - "\"%R%\" -e \"library('grplasso')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=grplasso
  license: GPL-2 and GPL-3
  summary: Fits user specified (GLM-) models with Group Lasso penalty
  license_family: GPL
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-2'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
