{% set version = "0.4-7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-grplasso
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/grplasso_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/grplasso/grplasso_{{ version }}.tar.gz
  sha256: 6a7801aabc87807247caba6fcb169efdaa1be6dab495213a8fcb34c3a042c449

build:
  noarch: generic
  number: 4
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('grplasso')"           # [not win]
    - "\"%R%\" -e \"library('grplasso')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=grplasso
  license: GPL-2.0-or-later
  summary: Fits user specified (GLM-) models with Group Lasso penalty
  license_family: GPL
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
