travis:
  secure:
    BINSTAR_TOKEN: VFsMZDR0kDM7JR0t6e5UaedDsez5z2pbcR8ZMjW0Vt99DlPF6q0pMBp1m0hloeH3XOKX1LC+sdo7tu6OYVVCDLihitNB7FgI2iYD+nlctEongznUiBgVA19uxBXoJdmgVQbg4jr7iqzLVZij6HoiVMnQia6D368hKGLpmfskQ5tTIUAyefnCh8SaD+xyPlOFsEjdUq6gfloXzV2DwOJTjd0uy/ywjLzuq82gvsJc05B+iMxEAUltaMYhi8jJx4lu+vwrOkb1L3nZC0xRO677lFUhtOYCwhsPCGfjvShcoun/1BAy3pgzTaR7q8w6kmoAe0F40aRji0krms83zRLEbkZdXkkqiIdhZ4DEyn7bCoxDmucXvPfSMVtucDUawwtpwWn7tqFTKF6nmNBXdBp1PqGuQoq8YEHMYtucj5vbeokmlXRwQ64BqNMqSF1V1ODWp1VZCKrakXITGcuv4m0RUdkYr8OUL07vFxxUsv8js+gQxdzls9Pk9RZs/Klbjtx77QAQrZPHTYHDe476OQdQL+SUo9KlFD1zKO3VKhkti9CuzDj0UrowhYlvQ6+YCTG4GyRL62O4ch7niGVO27WhWdfcKeJ1ZG5niLAzk292HuuO2HcgTJ/7gNn/uar+WFKoUGMrJHp4v1XhGKlD1XoOVLzLGWQpE6UzLBK6f9eV/9U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
