travis:
  secure:
    BINSTAR_TOKEN: qiask3gQIrMUH0PoajaSKrZ8/FMLqE3GKC2byhTMM3kOfKTe700S2OLEMyzFCA1tSxgZj1lSHbSDtQhcuX7M1zvCl/l5xU0BlMGUz8+1OJrgHzaTzIY7wpfQDFxGnhREd7kjVHpWvxSyo2mtEbyjqo+1JjYv5vyDk57C2oULCMUVnm4KdfA7c7eXSzd5poH8JkGP/qgiXj9zNSk+dhXStFppxXOKPpQ0aXhInf/p1REyPIAPyqHrvd6FkfbAhvFfkJMRTVAUYKPPIe/ouIFR7DMyr1yUCAR5khPfJuSUykjzkM5m7j/EQPsz1m+siN9cVJkHc7XZVJpdbo/Um/wMgBEOz/JAYEzk5kj5y9jehyLfN39JX0ojYuWtLvjOhlWhODncF10+26gbbQQNWuCCw3kBXkit+F91RCiWUF+S6JRAFB/m1+iJeZGtUsKhcBWx2d9Zfmx7MjOTu/6NMoqOe3uToZT5LiFztxPcOEIWnz5CxWkup9Mm5zRG/YUALLxilwENgZFX/iJMD4CpwACsM7oaYT035xEVBFDVbcIkn0fyHiVH2lokJdEvDuVmSjknphuD1sWG3vWlr3VbzgzhMwwJtvZ7fg9ip1ni4+I5mkJqBb77OPwiQx1tvPtPs1eaQD8AY+nKjEIyAbfY2YGiNcV2OKUonvInhST2NIairYk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
